[general]
color = "magenta"
interval = 500
blink = false
bold = true

[position]
horizontal = "center"
vertical = "center"

[date]
fmt = "%A, %B %d, %Y"
use_12h = false
utc = false
hide_seconds = false
