print_info() {
    put "System"
    puts "" title
    puts "" distro
    puts "" kernel 
    puts "󰏗" packages
    prin ───────────────────────────────────
    put "Hardware"
    puts "" cpu
    puts "" gpu
    puts "" memory
    puts "" resolution
    prin ───────────────────────────────────
    put "Profile"
    puts "󰖯" wm
    puts "T" term
    puts "" shell
    puts "󰅐" uptime
    prin ───────────────────────────────────
    colors
}

put() {
    prin "\n\n ${1}"
}

puts() {
    info "\n\n ${1}" ${2}
}

colors() {
    local color_output="\n \n"
    for i in {0..7}; do
        color_output+="$(color ${i})⬤ "
        color_output+="$(color ${i} + 8)⬤ "
        if [ $i -eq 3 ]; then
            color_output+="\n \n"   
        fi
    done
    prin "${color_output}"
}

title_fqdn="off"
kernel_shorthand="on"
distro_shorthand="off"
os_arch="on"
memory_percent="off"
memory_unit="mib"
speed_type="bios_limit"
speed_shorthand="off"
cpu_brand="on"
cpu_speed="on"
cpu_cores="logical"
cpu_temp="off"
gpu_brand="on"
gpu_type="all"
refresh_rate="off"
mpc_args=()
colors=(distro)
bold="on"
underline_enabled="on"
underline_char="-"
separator=" •"

# Backend Settings

image_backend="kitty"
image_source="logo.png"

# Ascii Options

ascii_distro="auto"
ascii_colors=(distro)
ascii_bold="on"

# Image Options

image_loop="off"
thumbnail_dir="${XDG_CACHE_HOME:-${HOME}/.cache}/thumbnails/neofetch"

crop_mode="normal"
crop_offset="center"
image_size="auto"
gap=3
yoffset=0
xoffset=0
background_color=

# Misc Options

stdout="off"
