# Key maps

source = keymaps.conf

# Monitors

monitor=,preferred,auto,auto

# Autostart

exec-once = sh $HOME/.config/hypr/slideshow.sh
exec-once = dunst & waybar & swww-daemon &

# Environment variables

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Look and feel

general { 
    gaps_in = 20
    gaps_out = 20
    border_size = 5

    col.active_border = rgb(f2d5cf) rgb(eebebe) 45deg
    col.inactive_border = rgba(babbf1aa)

    resize_on_border = true

    allow_tearing = false

    layout = dwindle
}

decoration {
    rounding = 10
    drop_shadow = true
    shadow_range = 20
    shadow_render_power = 15
    col.shadow = rgba(00000034)

    active_opacity = 1.0
    inactive_opacity = 1.0

    blur {
        enabled = true
        size = 3
        passes = 1
        
        vibrancy = 0.1696
    }
}

animations {
    enabled = true

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 2, default
    animation = workspaces, 1, 6, default
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_is_master = true
}

misc { 
    force_default_wallpaper = -1
    disable_hyprland_logo = false
}

# Input

input {
    kb_layout = de
    kb_variant = nodeadkeys
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0.4

    touchpad {
        natural_scroll = false
    }
}

gestures {
    workspace_swipe = false
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

# Windows and workspaces

windowrule = opacity 0.69 override 0.62 override 0.69 override,^(kitty)$
windowrulev2 = suppressevent maximize, class:.*
