general { 
    gaps_in = 20
    gaps_out = 20
    border_size = 5

    col.active_border = rgb(f2d5cf) rgb(eebebe) 45deg
    col.inactive_border = rgba(babbf1aa)

    resize_on_border = true

    allow_tearing = false

    layout = dwindle
}
