#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width  0
bspc config window_gap    20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
sh $HOME/.config/nitrogen/slideshow.sh &

polybar distro &
polybar workspaces &
polybar tray &
polybar date &
polybar hardware &
polybar power &
