require 'user.dashboard'
require 'user.key-bindings'
require 'user.options'
require 'user.plugins'
require 'user.settings'
require 'user.plugins.catppuccin'
require 'user.plugins.nvim-tree'
require 'user.plugins.rust-tools'
